
==== CDP Discovery

The CDP discovery is made walking the CISCO-CDP-MIB.
Please reviewing this MIB for getting more details.

NOTE: CdpGlobalGroupTracker.java

Required OID

[option="autowidth"]
|===
| Name                      | OID                           | Description
| _cdpGlobalRun_            | `.1.3.6.1.4.1.9.9.23.1.3.1.0` | An indication of whether the Cisco Discovery Protocol is currently running.
                                                              Entries in _cdpCacheTable_ are deleted when CDP is disabled.
| _cdpGlobalDeviceId_       | `.1.3.6.1.4.1.9.9.23.1.3.4.0` | The device ID advertised by this device.
                                                              The format of this device id is characterized by the value of _cdpGlobalDeviceIdFormat_ object.
| _cdpGlobalDeviceIdFormat_ | `.1.3.6.1.4.1.9.9.23.1.3.7.0` | An indication of the format of Device-Id contained in the corresponding instance of _cdpGlobalDeviceId_.
                                                              User can only specify the formats that the device is capable of as denoted in _cdpGlobalDeviceIdFormatCpb_ object. +
                                                              _serialNumber(1)_ indicates that the value of _cdpGlobalDeviceId_ object is in the form of an _ASCII_ string contain the device serial number. +
                                                              _macAddress(2)_ indicates that the value of _cdpGlobalDeviceId_ object is in the form of Layer 2 MAC address. +
                                                              _other(3)_ indicates that the value of _cdpGlobalDeviceId_ object is in the form of a platform specific _ASCII_ string contain info that identifies the device.
                                                              For example: _ASCII string_ contains _serialNumber_ appended/prepened with system name.
|===

[source, sql]
----
opennms=# \d cdpelement
                                     Table "public.cdpelement"
      Column        |           Type           |                     Modifiers
---------------------+--------------------------+----------------------------------------------------
id                  | integer                  | not null default nextval('opennmsnxtid'::regclass)
nodeid              | integer                  | not null
cdpglobalrun        | integer                  | not null
cdpglobaldeviceid   | text                     | not null
cdpnodecreatetime   | timestamp with time zone | not null
cdpnodelastpolltime | timestamp with time zone | not null
Indexes:
   "pk_cdpelement" PRIMARY KEY, btree (id)
   "cdp_deviceid_idx" btree (cdpglobaldeviceid)
   "cdpelement_nodeid_idx" btree (nodeid)
Foreign-key constraints:
   "fk_cdpelement_nodeid" FOREIGN KEY (nodeid) REFERENCES node(nodeid) ON DELETE CASCADE
----


[source, sql]
----
Table "public.cdplink"
        Column         |           Type           |                     Modifiers
------------------------+--------------------------+----------------------------------------------------
id                     | integer                  | not null default nextval('opennmsnxtid'::regclass)
nodeid                 | integer                  | not null
cdpcacheifindex        | integer                  | not null
cdpinterfacename       | text                     |
cdpcacheaddresstype    | integer                  | not null
cdpcacheaddress        | text                     | not null
cdpcacheversion        | text                     | not null
cdpcachedeviceid       | text                     | not null
cdpcachedeviceport     | text                     | not null
cdpcachedeviceplatform | text                     | not null
cdplinkcreatetime      | timestamp with time zone | not null
cdplinklastpolltime    | timestamp with time zone | not null
cdpcachedeviceindex    | integer                  | not null
Indexes:
   "pk_cdplink" PRIMARY KEY, btree (id)
   "cdplink_address_idx" btree (cdpcacheaddress)
   "cdplink_lastpoll_idx" btree (cdplinklastpolltime)
   "cdplink_nodeid_idx" btree (nodeid)
   "cdplink_pk_idx" btree (nodeid, cdpcachedeviceid, cdpcachedeviceport)
   "cdplink_pk_new_idx" btree (nodeid, cdpcacheifindex, cdpcachedeviceindex)
Foreign-key constraints:
   "fk_cdplink_nodeid" FOREIGN KEY (nodeid) REFERENCES node(nodeid) ON DELETE CASCADE
----
