
==== LLDP Discovery

[options="header, autowidth"]
|===
| Name                      | OID                       | Description
| _lldpLocChassisIdSubtype_ | `.1.0.8802.1.1.2.1.3.1.0` | The type of encoding used to identify the chassis associated with the local system.
| _lldpLocChassisId_        | `.1.0.8802.1.1.2.1.3.2.0` | The string value used to identify the chassis component associated with the local system.
| _lldpLocSysName_          | `.1.0.8802.1.1.2.1.3.3.0` | The string value used to identify the system name of the local system.
                                                          If the local agent supports link:http://tools.ietf.org/html/rfc3418[IETF RFC 3418], _lldpLocSysName_ object should have the same value of _sysName_ object.
|===

[source, sql]
----
opennms=# \d lldpelement
                                     Table "public.lldpelement"
       Column        |           Type           |                     Modifiers
----------------------+--------------------------+----------------------------------------------------
id                   | integer                  | not null default nextval('opennmsnxtid'::regclass)
nodeid               | integer                  | not null
lldpchassisid        | text                     | not null
lldpchassisidsubtype | integer                  | not null
lldpsysname          | text                     | not null
lldpnodecreatetime   | timestamp with time zone | not null
lldpnodelastpolltime | timestamp with time zone | not null
Indexes:
   "pk_lldpelement" PRIMARY KEY, btree (id)
   "lldp_chassis_idx" btree (lldpchassisid)
   "lldp_sysname_idx" btree (lldpsysname)
   "lldpelement_nodeid_idx" btree (nodeid)
Foreign-key constraints:
   "fk_lldpelement_nodeid" FOREIGN KEY (nodeid) REFERENCES node(nodeid) ON DELETE CASCADE
----

[source, sql]
----
opennms=# \d lldplink
                                        Table "public.lldplink"
        Column          |           Type           |                     Modifiers
-------------------------+--------------------------+----------------------------------------------------
id                      | integer                  | not null default nextval('opennmsnxtid'::regclass)
nodeid                  | integer                  | not null
lldplocalportnum        | integer                  | not null
lldpportid              | text                     | not null
lldpportidsubtype       | integer                  | not null
lldpportdescr           | text                     | not null
lldpportifindex         | integer                  |
lldpremchassisid        | text                     | not null
lldpremchassisidsubtype | integer                  | not null
lldpremsysname          | text                     | not null
lldpremportid           | text                     | not null
lldpremportidsubtype    | integer                  | not null
----
