
=== Topology Discovery

_Enhanced Linkd_ (enlinkd) has been designed to get a snapshot of the neighbors from the device point of view.
Essentially it asks each device the following question: "What is the network topology from your point of view".
From this point of view this will only provide local topology discovery features.
It does not attempt to discover global topology or doing any correlation with the data coming from other nodes.

Actually it supports linkd discovery for the following protocols:

* Layer 2 protocols link:https://en.wikipedia.org/wiki/Link_Layer_Discovery_Protocol[Link Layer Discovery Protocol] (LLDP), link:https://en.wikipedia.org/wiki/Cisco_Discovery_Protocol[Cisco Discovery Protocol] (CDP) and transparent bridge discovery
* Layer 3 protocols link:https://en.wikipedia.org/wiki/Open_Shortest_Path_First[Open Shortest Path First] (OSPF) and link:https://en.wikipedia.org/wiki/IS-IS[Intermediate System to Intermediate System] (IS-IS)

The general strategy it does its work is walk SNMP data and persist data into the OpenNMS database table.
There is a 1:1 relation between SNMP scalars and tables with database tables.
We adapt a strictly walk and persist strategy.

==== Configuring enlinkd

==== User checklist / Troubleshooting
